import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import openapiTS, { astToString } from "openapi-typescript";
import type { OpenAPI3 } from "openapi-typescript";
import { createOpenApiDocument } from "../../../apps/admin/server/openapi/document";

const outputPath = resolve(import.meta.dirname, "../src/generated.ts");
const document = createOpenApiDocument();
const ast = await openapiTS(document as unknown as OpenAPI3);
const output = `// This file is generated by packages/api-client/scripts/generate.ts.\n// Do not edit it directly.\n\n${astToString(ast)}`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  const expected = await formatOutput(output);
  if (current !== expected) {
    console.error("@openscene-ai/api-client is out of date. Run: bun run generate");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, await formatOutput(output));
}

async function formatOutput(value: string): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), "openscene-api-client-"));
  const candidate = join(directory, "generated.ts");
  try {
    await writeFile(candidate, value);
    execFileSync("vp", ["fmt", candidate], { cwd: resolve(import.meta.dirname, "..") });
    return await readFile(candidate, "utf8");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}
