// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "zh-CN";

export type Locales = "en-US" | "zh-CN";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * 保​存
     */
    save: string;
    /**
     * 撤​销
     */
    undo: string;
    /**
     * 重​做
     */
    redo: string;
    /**
     * 删​除
     */
    delete: string;
    /**
     * 完​成
     */
    done: string;
    /**
     * 搜​索​物​料​组​件​…
     */
    searchComponent: string;
    /**
     * 占​位​符
     */
    placeholder: string;
  };
  sidebar: {
    /**
     * 页​面
     */
    pages: string;
    /**
     * 物​料​契​约
     */
    agents: string;
    /**
     * 变​量​与​语​言
     */
    variables: string;
    /**
     * 动​作​事​件
     */
    actions: string;
    /**
     * 收​起​面​板
     */
    collapse: string;
    /**
     * 展​开​大​纲
     */
    expand: string;
    /**
     * 展​开​属​性​面​板
     */
    expandProperties: string;
    /**
     * 页​面​与​图​层​大​纲
     */
    pagesTabTooltip: string;
    /**
     * 物​料​契​约
     */
    agentsTabTooltip: string;
    /**
     * 变​量​与​国​际​化
     */
    variablesTabTooltip: string;
    /**
     * 动​作​与​事​件​库
     */
    actionsTabTooltip: string;
  };
  panels: {
    pages: {
      /**
       * 页​面
       */
      pages: string;
      /**
       * 图​层
       */
      layers: string;
      /**
       * {​c​o​u​n​t​}​ ​个​节​点
       * @param {number} count
       */
      nodeCount: RequiredParams<"count">;
      /**
       * 当​前​文​档​为​空​。​添​加​第​一​个​ ​A​p​p​ ​节​点​后​，​它​会​成​为​ ​r​o​o​t​。
       */
      emptyDoc: string;
    };
    agents: {
      /**
       * A​I​ ​智​能​助​手
       */
      title: string;
      /**
       * 向​ ​A​I​ ​提​问​、​生​成​组​件​或​按​绑​定​的​提​示​词​模​块​辅​助​页​面​搭​建​。
       */
      description: string;
      /**
       * 新​建​对​话
       */
      newChat: string;
      /**
       * 会​话​列​表
       */
      sessionsList: string;
      /**
       * 重​命​名
       */
      rename: string;
      /**
       * 输​入​新​会​话​名​称
       */
      renameSessionPrompt: string;
      /**
       * {​c​o​u​n​t​}​ ​条​消​息
       * @param {unknown} count
       */
      messagesCount: RequiredParams<"count">;
      /**
       * 暂​无​对​话​会​话
       */
      noSessions: string;
      /**
       * 开​始​新​的​对​话
       */
      startChat: string;
      /**
       * 向​ ​A​I​ ​助​手​提​问​或​输​入​指​令​…​（​S​h​i​f​t​+​E​n​t​e​r​ ​换​行​）
       */
      inputPlaceholder: string;
      /**
       * 发​送
       */
      send: string;
      /**
       * 停​止
       */
      stop: string;
      /**
       * 提​示​词​配​置
       */
      promptProfile: string;
      /**
       * 默​认​提​示​词
       */
      defaultProfile: string;
      /**
       * 附​件
       */
      attachments: string;
      /**
       * 添​加​附​件
       */
      addAttachment: string;
      /**
       * 移​除​附​件
       */
      removeAttachment: string;
      /**
       * 删​除​会​话
       */
      deleteSession: string;
      /**
       * 携​带​选​中​元​素
       */
      attachElementContext: string;
      /**
       * 已​选​中
       */
      selectedElement: string;
      /**
       * 已​附​加​目​标​元​素​上​下​文
       */
      targetedPromptTip: string;
      /**
       * 清​空​消​息
       */
      clearChat: string;
      /**
       * 复​制​消​息
       */
      copyMessage: string;
      /**
       * 已​复​制​！
       */
      copied: string;
      /**
       * 已​生​成​页​面​ ​U​I​ ​规​范
       */
      uiDocumentDetected: string;
      /**
       * 应​用​到​画​布
       */
      applyToCanvas: string;
      /**
       * 已​成​功​应​用​到​页​面​画​布​！
       */
      appliedToCanvasSuccess: string;
      /**
       * 个​组​件​元​素
       */
      elementsCount: string;
      /**
       * 查​看​ ​J​S​O​N​ ​规​范
       */
      viewJson: string;
      /**
       * 隐​藏​ ​J​S​O​N
       */
      hideJson: string;
      /**
       * A​p​p​ ​标​识
       */
      appKey: string;
      /**
       * 协​议​版​本
       */
      manifestVersion: string;
      /**
       * 组​件​种​类
       */
      componentTypes: string;
      /**
       * {​c​o​u​n​t​}​ ​种
       * @param {unknown} count
       */
      componentCount: RequiredParams<"count">;
      /**
       * 契​约​状​态
       */
      status: string;
      /**
       * 已​通​过
       */
      valid: string;
      /**
       * 待​审​核
       */
      needsReview: string;
      /**
       * 修​订​版​本​ ​{​r​e​v​}
       * @param {unknown} rev
       */
      rev: RequiredParams<"rev">;
      /**
       * 契​约​诊​断​信​息
       */
      diagnostics: string;
      /**
       * 提​示​词​与​上​下​文​调​试
       */
      promptInspector: string;
      /**
       * 查​看​后​端​组​装​的​完​整​系​统​提​示​词​、​用​户​会​话​历​史​与​实​时​上​下​文​。
       */
      promptInspectorDesc: string;
      /**
       * 全​部​消​息​ ​(​时​间​线​)
       */
      allTimelineTab: string;
      /**
       * 完​整​系​统​提​示​词
       */
      systemPromptTab: string;
      /**
       * 基​础​提​示​词
       */
      basePromptTab: string;
      /**
       * 注​入​组​件
       */
      injectedComponentsTab: string;
      /**
       * 用​户​与​上​下​文
       */
      userContextTab: string;
      /**
       * 请​求​数​据​包
       */
      rawPayloadTab: string;
      /**
       * M​D​ ​文​档​模​式
       */
      viewModeMarkdown: string;
      /**
       * 原​始​代​码
       */
      viewModeRaw: string;
      /**
       * 提​示​词​拆​解
       */
      breakdown: string;
      /**
       * 全​局​底​层​提​示​词
       */
      globalPrompt: string;
      /**
       * 应​用​基​础​提​示​词
       */
      appSystem: string;
      /**
       * 目​标​元​素​上​下​文
       */
      selectedElementContext: string;
      /**
       * 注​入​组​件​清​单
       */
      injectedComponents: string;
      /**
       * 注​入​ ​O​p​e​n​A​P​I​ ​接​口
       */
      injectedOpenApi: string;
      /**
       * 当​前​提​示​词​配​置​未​注​入​物​料​组​件
       */
      noInjectedComponents: string;
      /**
       * 当​前​提​示​词​配​置​未​注​入​ ​O​p​e​n​A​P​I​ ​接​口
       */
      noInjectedOpenApi: string;
      /**
       * 获​取​最​新​提​示​词
       */
      fetchPrompt: string;
      /**
       * 正​在​获​取​提​示​词​.​.​.
       */
      fetchingPrompt: string;
      /**
       * 复​制​提​示​词
       */
      copyPrompt: string;
      /**
       * {​c​o​u​n​t​}​ ​字​符
       * @param {unknown} count
       */
      charsCount: RequiredParams<"count">;
      /**
       * 约​ ​{​c​o​u​n​t​}​ ​t​o​k​e​n​s
       * @param {unknown} count
       */
      estimatedTokens: RequiredParams<"count">;
      /**
       * 开​发​者​调​试
       */
      devModeOnly: string;
      /**
       * 查​看​提​示​词​与​调​试​信​息
       */
      openInspector: string;
    };
    tools: {
      /**
       * 可​视​化​编​辑​模​式
       */
      visual: string;
      /**
       * 文​档​编​辑​模​式
       */
      text: string;
      /**
       * 开​发​者​模​式
       */
      developer: string;
      /**
       * 预​览​模​式
       */
      preview: string;
    };
    actions: {
      /**
       * 动​作​库
       */
      title: string;
      /**
       * 定​义​和​管​理​可​被​组​件​直​接​绑​定​的​动​作​与​状​态​事​件​处​理​器​。
       */
      description: string;
      /**
       * 搜​索​动​作​标​识​、​标​题​或​类​型​.​.​.
       */
      searchPlaceholder: string;
      /**
       * 新​建​动​作
       */
      addAction: string;
      /**
       * 编​辑​动​作
       */
      editAction: string;
      /**
       * 删​除​动​作
       */
      deleteAction: string;
      /**
       * 动​作​标​识​ ​(​K​e​y​)
       */
      actionKey: string;
      /**
       * 例​如​ ​t​o​g​g​l​e​M​o​d​a​l​,​ ​u​p​d​a​t​e​C​o​u​n​t
       */
      actionKeyPlaceholder: string;
      /**
       * 动​作​名​称
       */
      actionTitle: string;
      /**
       * 例​如​ ​切​换​弹​窗​显​示
       */
      actionTitlePlaceholder: string;
      /**
       * 动​作​描​述
       */
      actionDesc: string;
      /**
       * 动​作​类​型
       */
      actionType: string;
      /**
       * 修​改​状​态​ ​(​s​e​t​S​t​a​t​e​)
       */
      typeSetState: string;
      /**
       * 自​定​义​处​理​器​ ​(​C​u​s​t​o​m​)
       */
      typeCustom: string;
      /**
       * 目​标​状​态​变​量
       */
      targetVariable: string;
      /**
       * 目​标​值
       */
      targetValue: string;
      /**
       * 取​反​切​换​ ​(​!​t​o​g​g​l​e​)
       */
      toggleOption: string;
      /**
       * 设​为​ ​t​r​u​e
       */
      trueOption: string;
      /**
       * 设​为​ ​f​a​l​s​e
       */
      falseOption: string;
      /**
       * 自​定​义​值
       */
      customValue: string;
      /**
       * {​c​o​u​n​t​}​ ​处​组​件​绑​定
       * @param {unknown} count
       */
      referencesCount: RequiredParams<"count">;
      /**
       * 未​被​组​件​绑​定
       */
      noReferences: string;
      /**
       * 绑​定​该​动​作​的​组​件​与​事​件
       */
      referencesTitle: string;
      /**
       * 确​认​删​除​动​作
       */
      confirmDeleteTitle: string;
      /**
       * 确​定​要​删​除​动​作​“​{​n​a​m​e​}​”​吗​？
       * @param {unknown} name
       */
      confirmDelete: RequiredParams<"name">;
      /**
       * 动​作​“​{​n​a​m​e​}​”​当​前​正​被​ ​{​c​o​u​n​t​}​ ​处​组​件​事​件​绑​定​，​删​除​可​能​导​致​点​击​交​互​失​效​。​确​定​继​续​吗​？
       * @param {unknown} count
       * @param {unknown} name
       */
      confirmDeleteWithRefs: RequiredParams<"count" | "name">;
      /**
       * 暂​无​动​作​定​义
       */
      emptyTitle: string;
      /**
       * 创​建​预​设​动​作​或​状​态​更​新​逻​辑​，​让​按​钮​等​组​件​能​够​一​键​直​接​绑​定​。
       */
      emptyDesc: string;
      /**
       * 系​统​内​置
       */
      builtInBadge: string;
      /**
       * 自​定​义
       */
      customBadge: string;
      /**
       * {​c​o​u​n​t​}​ ​个​动​作
       * @param {unknown} count
       */
      actionCount: RequiredParams<"count">;
      /**
       * 参​数​配​置​ ​(​J​S​O​N​)
       */
      paramsJson: string;
    };
    variables: {
      /**
       * 预​览​语​言​ ​(​i​1​8​n​)
       */
      locales: string;
      /**
       * 状​态​变​量
       */
      title: string;
      /**
       * 搜​索​变​量​名​或​值​.​.​.
       */
      searchPlaceholder: string;
      /**
       * 新​建​变​量
       */
      addVariable: string;
      /**
       * 编​辑​变​量
       */
      editVariable: string;
      /**
       * 重​命​名​变​量
       */
      renameVariable: string;
      /**
       * 删​除​变​量
       */
      deleteVariable: string;
      /**
       * 变​量​名
       */
      variableName: string;
      /**
       * 类​型
       */
      variableType: string;
      /**
       * 变​量​值
       */
      variableValue: string;
      /**
       * 例​如​ ​c​o​u​n​t​e​r​,​ ​u​s​e​r​N​a​m​e
       */
      variableKeyPlaceholder: string;
      /**
       * 变​量​名​必​须​是​合​法​标​识​符​（​字​母​、​数​字​、​_​、​$​）
       */
      invalidKey: string;
      /**
       * 变​量​名​不​能​使​用​保​留​关​键​字​ ​(​i​1​8​n​,​ ​l​a​n​g​,​ ​_​_​s​c​e​n​e​)
       */
      reservedKey: string;
      /**
       * 该​变​量​名​已​存​在
       */
      duplicateKey: string;
      /**
       * 暂​无​状​态​变​量
       */
      emptyStateTitle: string;
      /**
       * 创​建​状​态​变​量​，​在​组​件​属​性​中​进​行​数​据​绑​定​、​条​件​判​断​与​模​板​计​算​。
       */
      emptyStateDesc: string;
      /**
       * {​c​o​u​n​t​}​ ​处​组​件​引​用
       * @param {unknown} count
       */
      referencesCount: RequiredParams<"count">;
      /**
       * 未​被​组​件​引​用
       */
      noReferences: string;
      /**
       * 引​用​该​变​量​的​组​件
       */
      referencesTitle: string;
      /**
       * 确​认​删​除​变​量
       */
      confirmDeleteTitle: string;
      /**
       * 确​定​要​删​除​变​量​“​{​n​a​m​e​}​”​吗​？
       * @param {unknown} name
       */
      confirmDelete: RequiredParams<"name">;
      /**
       * 变​量​“​{​n​a​m​e​}​”​当​前​正​被​ ​{​c​o​u​n​t​}​ ​处​组​件​引​用​。​删​除​可​能​导​致​动​态​绑​定​失​效​。​确​定​继​续​吗​？
       * @param {unknown} count
       * @param {unknown} name
       */
      confirmDeleteWithRefs: RequiredParams<"count" | "name">;
      /**
       * 文​本​ ​(​s​t​r​i​n​g​)
       */
      typeString: string;
      /**
       * 数​值​ ​(​n​u​m​b​e​r​)
       */
      typeNumber: string;
      /**
       * 布​尔​ ​(​b​o​o​l​e​a​n​)
       */
      typeBoolean: string;
      /**
       * 对​象​ ​(​o​b​j​e​c​t​)
       */
      typeObject: string;
      /**
       * 数​组​ ​(​a​r​r​a​y​)
       */
      typeArray: string;
      /**
       * 空​值​ ​(​n​u​l​l​)
       */
      typeNull: string;
      /**
       * J​S​O​N​ ​格​式​错​误​，​请​检​查​语​法
       */
      jsonInvalid: string;
      /**
       * 复​制​状​态​路​径
       */
      copyPath: string;
      /**
       * 已​复​制​状​态​路​径
       */
      pathCopied: string;
      /**
       * 复​制​变​量
       */
      duplicate: string;
      /**
       * 保​存
       */
      save: string;
      /**
       * 取​消
       */
      cancel: string;
      /**
       * 删​除
       */
      delete: string;
      /**
       * 创​建
       */
      create: string;
      /**
       * {​c​o​u​n​t​}​ ​个​变​量
       * @param {unknown} count
       */
      variableCount: RequiredParams<"count">;
      /**
       * i​1​8​n​ ​文​本
       */
      localesTab: string;
      /**
       * 状​态​变​量
       */
      variablesTab: string;
      /**
       * 格​式​化​ ​J​S​O​N
       */
      formatJson: string;
      /**
       * 展​开​查​看
       */
      expandJson: string;
      /**
       * 收​起
       */
      collapseJson: string;
      /**
       * 搜​索​语​言​名​称​或​代​号​.​.​.
       */
      searchLocalesPlaceholder: string;
      /**
       * 刷​新​语​言​选​项
       */
      refreshLocales: string;
      /**
       * 默​认
       */
      defaultLocaleBadge: string;
      /**
       * 服​务​器​应​用​语​言
       */
      serverLocalesTitle: string;
      /**
       * 未​找​到​匹​配​的​语​言
       */
      noLocalesFound: string;
      /**
       * 添​加​语​言​变​量​ ​(​l​a​n​g​)
       */
      addLangVariable: string;
      /**
       * 系​统​保​护
       */
      langBadge: string;
      /**
       * 当​前​运​行​时​的​语​言​代​码​，​仅​可​选​择​应​用​支​持​的​语​言
       */
      langVariableDesc: string;
      /**
       * 确​定​要​从​状​态​中​移​除​语​言​变​量​ ​(​l​a​n​g​)​ ​吗​？
       */
      confirmDeleteLang: string;
      /**
       * 新​建​键
       */
      addI18nKey: string;
      /**
       * 编​辑​键
       */
      editI18nKey: string;
      /**
       * 重​命​名​键
       */
      renameI18nKey: string;
      /**
       * 删​除​键
       */
      deleteI18nKey: string;
      /**
       * 文​本​键​名
       */
      i18nKeyName: string;
      /**
       * 文​本​内​容
       */
      i18nKeyValue: string;
      /**
       * 例​如​ ​g​r​e​e​t​i​n​g​,​ ​h​o​m​e​.​t​i​t​l​e
       */
      i18nKeyPlaceholder: string;
      /**
       * 输​入​当​前​语​言​的​文​本​内​容​.​.​.
       */
      i18nValuePlaceholder: string;
      /**
       * 暂​无​ ​i​1​8​n​ ​文​本​键
       */
      emptyI18nTitle: string;
      /**
       * 创​建​ ​i​1​8​n​ ​文​本​键​，​支​持​多​语​言​动​态​切​换​与​翻​译​文​本​管​理​。
       */
      emptyI18nDesc: string;
      /**
       * 搜​索​键​名​或​文​本​内​容​.​.​.
       */
      searchI18nPlaceholder: string;
      /**
       * 当​前​编​辑​语​言
       */
      currentLocale: string;
      /**
       * 默​认​语​言
       */
      defaultLocaleHint: string;
      /**
       * 默​认​值​:​ ​{​v​a​l​}
       * @param {unknown} val
       */
      fallbackHint: RequiredParams<"val">;
      /**
       * 未​翻​译
       */
      untranslated: string;
      /**
       * 确​认​删​除​ ​i​1​8​n​ ​键
       */
      confirmDeleteI18nTitle: string;
      /**
       * 确​定​要​从​所​有​语​言​中​删​除​键​“​{​k​e​y​}​”​吗​？
       * @param {unknown} key
       */
      confirmDeleteI18n: RequiredParams<"key">;
      /**
       * 键​“​{​k​e​y​}​”​当​前​正​被​ ​{​c​o​u​n​t​}​ ​处​组​件​引​用​。​删​除​可​能​导​致​翻​译​缺​失​。​确​定​继​续​吗​？
       * @param {unknown} count
       * @param {unknown} key
       */
      confirmDeleteI18nWithRefs: RequiredParams<"count" | "key">;
      /**
       * {​c​o​u​n​t​}​ ​个​键
       * @param {unknown} count
       */
      i18nKeyCount: RequiredParams<"count">;
      /**
       * 复​制​ ​i​1​8​n​ ​绑​定​表​达​式​ ​(​$​t​)
       */
      copyI18nPath: string;
      /**
       * 已​复​制​ ​i​1​8​n​ ​表​达​式
       */
      i18nPathCopied: string;
      /**
       * 选​择​语​言
       */
      selectLocale: string;
    };
  };
  toolbar: {
    /**
     * 选​择
     */
    select: string;
    /**
     * 交​互
     */
    interact: string;
    /**
     * 平​移
     */
    pan: string;
    /**
     * 缩​放​比​例
     */
    zoom: string;
    /**
     * 旋​转​设​备
     */
    rotate: string;
    /**
     * 恢​复​设​备​方​向
     */
    restoreOrientation: string;
    /**
     * 操​作
     */
    actions: string;
    /**
     * 全​部
     */
    all: string;
    /**
     * 组​件
     */
    components: string;
    /**
     * 未​找​到​组​件​。
     */
    noComponents: string;
  };
  menu: {
    /**
     * 文​件
     */
    file: string;
    /**
     * 编​辑
     */
    edit: string;
    /**
     * 视​图
     */
    view: string;
    /**
     * 偏​好​设​置
     */
    preferences: string;
    /**
     * 外​观​主​题
     */
    theme: string;
    /**
     * 界​面​语​言
     */
    language: string;
    /**
     * 简​体​中​文
     */
    chinese: string;
    /**
     * E​n​g​l​i​s​h
     */
    english: string;
    /**
     * 保​存​文​档
     */
    saveDocument: string;
    /**
     * 复​制​ ​J​S​O​N​ ​快​照
     */
    copyJson: string;
    /**
     * 撤​销
     */
    undo: string;
    /**
     * 重​做
     */
    redo: string;
    /**
     * 框​架​尺​寸
     */
    frameSize: string;
    /**
     * 设​备​方​向
     */
    orientation: string;
    /**
     * 竖​向​ ​(​P​o​r​t​r​a​i​t​)
     */
    portrait: string;
    /**
     * 横​向​ ​(​L​a​n​d​s​c​a​p​e​)
     */
    landscape: string;
    /**
     * 旋​转​方​向
     */
    rotateOrientation: string;
    /**
     * 手​机​尺​寸
     */
    mobileCategory: string;
    /**
     * 平​板​尺​寸
     */
    tabletCategory: string;
    /**
     * 电​脑​/​桌​面​尺​寸
     */
    desktopCategory: string;
    /**
     * 缩​放​比​例​ ​(​{​p​e​r​c​e​n​t​}​%​)
     * @param {number} percent
     */
    zoomRatio: RequiredParams<"percent">;
    /**
     * 放​大
     */
    zoomIn: string;
    /**
     * 缩​小
     */
    zoomOut: string;
    /**
     * 缩​放​到​ ​1​0​0​%
     */
    zoom100: string;
    /**
     * 快​捷​键​列​表
     */
    shortcuts: string;
    /**
     * 浅​色​模​式
     */
    light: string;
    /**
     * 深​色​模​式
     */
    dark: string;
    /**
     * 跟​随​系​统
     */
    system: string;
    /**
     * 展​开​大​纲​面​板
     */
    expandSidebar: string;
    /**
     * 折​叠​大​纲​面​板
     */
    collapseSidebar: string;
    /**
     * 显​示​背​景​图​案
     */
    backgroundPattern: string;
    /**
     * 画​布​设​置​…
     */
    canvasSettings: string;
  };
  canvasSettings: {
    /**
     * 画​布​设​置
     */
    title: string;
    /**
     * 配​置​画​布​的​显​示​与​交​互​行​为​。
     */
    description: string;
    /**
     * 背​景
     */
    background: string;
    /**
     * 控​制​画​布​编​辑​区​域​的​背​景​纹​理​显​示​与​样​式​。
     */
    backgroundDescription: string;
    /**
     * 纹​理
     */
    texture: string;
    /**
     * 波​点
     */
    dots: string;
    /**
     * 网​格
     */
    grid: string;
  };
  properties: {
    /**
     * 属​性
     */
    title: string;
    /**
     * 选​择​节​点​后​编​辑​目​标​ ​A​p​p​ ​提​供​的​属​性​ ​M​e​t​a​。
     */
    empty: string;
    /**
     * 图​层​名​称
     */
    layerName: string;
    /**
     * 条​件​显​示​ ​(​V​i​s​i​b​i​l​i​t​y​)
     */
    visibilityTitle: string;
    /**
     * 绑​定​状​态​变​量​或​布​尔​表​达​式​，​值​为​真​时​渲​染​展​示​该​组​件​。
     */
    visibilityDesc: string;
    /**
     * 配​置​条​件​显​示
     */
    configureVisibility: string;
    /**
     * 重​置​ ​(​始​终​显​示​)
     */
    resetVisibility: string;
    /**
     * 事​件​与​动​作​ ​(​E​v​e​n​t​s​)
     */
    eventsTitle: string;
    /**
     * 绑​定​动​作
     */
    bindAction: string;
    /**
     * 未​配​置​动​作
     */
    noAction: string;
    /**
     * 修​改​状​态​ ​(​s​e​t​S​t​a​t​e​)
     */
    actionSetState: string;
    /**
     * 选​择​要​修​改​的​状​态​变​量
     */
    selectVariable: string;
    /**
     * 目​标​值
     */
    targetValue: string;
    /**
     * 取​反​切​换​ ​(​!​t​o​g​g​l​e​)
     */
    toggleBoolean: string;
    /**
     * 画​布​通​过​目​标​ ​A​p​p​ ​i​f​r​a​m​e​ ​进​行​沙​箱​渲​染​。​S​t​u​d​i​o​ ​仅​通​过​ ​P​r​e​v​i​e​w​ ​B​r​i​d​g​e​ ​传​递​文​档​快​照​。
     */
    runtimeDesc: string;
    openapi: {
      /**
       * O​p​e​n​A​P​I​ ​文​档
       */
      docs: string;
      /**
       * 当​前​ ​A​p​p​ ​没​有​ ​O​p​e​n​A​P​I​ ​文​档​，​请​先​在​ ​A​d​m​i​n​ ​中​添​加​。
       */
      noDocs: string;
      /**
       * O​p​e​n​A​P​I​ ​文​档​加​载​失​败
       */
      loadFailed: string;
      /**
       * 内​嵌​文​档
       */
      embedded: string;
      /**
       * 接​口​路​径
       */
      operation: string;
      /**
       * 请​求​方​式
       */
      method: string;
      /**
       * 路​径​参​数
       */
      pathParams: string;
      /**
       * 查​询​参​数
       */
      queryParams: string;
      /**
       * 请​求​体​ ​J​S​O​N
       */
      body: string;
      /**
       * 加​载​中​…
       */
      loading: string;
      /**
       * J​S​O​N​ ​格​式​暂​时​无​效
       */
      invalidJson: string;
    };
  };
  status: {
    /**
     * 正​在​加​载​ ​A​p​p​ ​会​话
     */
    loadingTitle: string;
    /**
     * S​t​u​d​i​o​ ​正​在​等​待​目​标​ ​A​p​p​ ​引​导​信​息​及​其​物​料​契​约​响​应​。
     */
    loadingDesc: string;
    /**
     * 请​从​目​标​ ​A​p​p​ ​打​开​ ​S​t​u​d​i​o
     */
    standaloneTitle: string;
    /**
     * S​t​u​d​i​o​ ​采​用​无​状​态​架​构​设​计​。​请​通​过​ ​O​p​e​n​S​c​e​n​e​ ​S​t​u​d​i​o​ ​会​话​从​目​标​ ​A​p​p​ ​启​动​，​以​便​提​供​文​档​、​物​料​清​册​及​ ​i​f​r​a​m​e​ ​预​览​环​境​。
     */
    standaloneDesc: string;
    /**
     * 缺​少​必​要​参​数​ ​s​e​r​v​e​r​-​u​r​l
     */
    missingServerUrlTitle: string;
    /**
     * S​t​u​d​i​o​ ​遵​循​无​本​地​存​储​架​构​，​不​内​置​任​何​默​认​后​端​地​址​。​必​须​通​过​ ​U​R​L​ ​q​u​e​r​y​ ​参​数​显​式​提​供​目​标​后​端​服​务​地​址​，​例​如​：​?​s​e​r​v​e​r​-​u​r​l​=​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​0​&​s​e​s​s​i​o​n​I​d​=​.​.​.​#​t​o​k​e​n​=​.​.​.
     */
    missingServerUrlDesc: string;
    /**
     * S​t​u​d​i​o​ ​会​话​不​可​用
     */
    sessionUnavailableTitle: string;
  };
  notices: {
    /**
     * 已​复​制​ ​J​S​O​N​ ​快​照​到​剪​贴​板
     */
    jsonCopied: string;
    /**
     * 已​向​目​标​ ​A​p​p​ ​发​送​保​存​指​令
     */
    saveSent: string;
    /**
     * 本​地​临​时​会​话​修​改​未​持​久​化​保​存
     */
    saveNotPersisted: string;
  };
  shortcuts: {
    /**
     * 快​捷​键​指​南
     */
    title: string;
    /**
     * 快​速​切​换​模​式​和​管​理​当​前​编​辑​会​话​。
     */
    description: string;
    /**
     * 可​视​化​编​辑​模​式
     */
    visualMode: string;
    /**
     * 文​档​编​辑​模​式
     */
    textMode: string;
    /**
     * 开​发​者​模​式
     */
    developerMode: string;
    /**
     * 预​览​模​式
     */
    previewMode: string;
    /**
     * 撤​销​ ​/​ ​重​做
     */
    undoRedo: string;
    /**
     * 保​存​文​档
     */
    save: string;
    /**
     * 复​制​ ​J​S​O​N​ ​快​照
     */
    copyJson: string;
    /**
     * 关​闭​菜​单​或​弹​窗
     */
    close: string;
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * 保存
     */
    save: () => LocalizedString;
    /**
     * 撤销
     */
    undo: () => LocalizedString;
    /**
     * 重做
     */
    redo: () => LocalizedString;
    /**
     * 删除
     */
    delete: () => LocalizedString;
    /**
     * 完成
     */
    done: () => LocalizedString;
    /**
     * 搜索物料组件…
     */
    searchComponent: () => LocalizedString;
    /**
     * 占位符
     */
    placeholder: () => LocalizedString;
  };
  sidebar: {
    /**
     * 页面
     */
    pages: () => LocalizedString;
    /**
     * 物料契约
     */
    agents: () => LocalizedString;
    /**
     * 变量与语言
     */
    variables: () => LocalizedString;
    /**
     * 动作事件
     */
    actions: () => LocalizedString;
    /**
     * 收起面板
     */
    collapse: () => LocalizedString;
    /**
     * 展开大纲
     */
    expand: () => LocalizedString;
    /**
     * 展开属性面板
     */
    expandProperties: () => LocalizedString;
    /**
     * 页面与图层大纲
     */
    pagesTabTooltip: () => LocalizedString;
    /**
     * 物料契约
     */
    agentsTabTooltip: () => LocalizedString;
    /**
     * 变量与国际化
     */
    variablesTabTooltip: () => LocalizedString;
    /**
     * 动作与事件库
     */
    actionsTabTooltip: () => LocalizedString;
  };
  panels: {
    pages: {
      /**
       * 页面
       */
      pages: () => LocalizedString;
      /**
       * 图层
       */
      layers: () => LocalizedString;
      /**
       * {count} 个节点
       */
      nodeCount: (arg: { count: number }) => LocalizedString;
      /**
       * 当前文档为空。添加第一个 App 节点后，它会成为 root。
       */
      emptyDoc: () => LocalizedString;
    };
    agents: {
      /**
       * AI 智能助手
       */
      title: () => LocalizedString;
      /**
       * 向 AI 提问、生成组件或按绑定的提示词模块辅助页面搭建。
       */
      description: () => LocalizedString;
      /**
       * 新建对话
       */
      newChat: () => LocalizedString;
      /**
       * 会话列表
       */
      sessionsList: () => LocalizedString;
      /**
       * 重命名
       */
      rename: () => LocalizedString;
      /**
       * 输入新会话名称
       */
      renameSessionPrompt: () => LocalizedString;
      /**
       * {count} 条消息
       */
      messagesCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 暂无对话会话
       */
      noSessions: () => LocalizedString;
      /**
       * 开始新的对话
       */
      startChat: () => LocalizedString;
      /**
       * 向 AI 助手提问或输入指令…（Shift+Enter 换行）
       */
      inputPlaceholder: () => LocalizedString;
      /**
       * 发送
       */
      send: () => LocalizedString;
      /**
       * 停止
       */
      stop: () => LocalizedString;
      /**
       * 提示词配置
       */
      promptProfile: () => LocalizedString;
      /**
       * 默认提示词
       */
      defaultProfile: () => LocalizedString;
      /**
       * 附件
       */
      attachments: () => LocalizedString;
      /**
       * 添加附件
       */
      addAttachment: () => LocalizedString;
      /**
       * 移除附件
       */
      removeAttachment: () => LocalizedString;
      /**
       * 删除会话
       */
      deleteSession: () => LocalizedString;
      /**
       * 携带选中元素
       */
      attachElementContext: () => LocalizedString;
      /**
       * 已选中
       */
      selectedElement: () => LocalizedString;
      /**
       * 已附加目标元素上下文
       */
      targetedPromptTip: () => LocalizedString;
      /**
       * 清空消息
       */
      clearChat: () => LocalizedString;
      /**
       * 复制消息
       */
      copyMessage: () => LocalizedString;
      /**
       * 已复制！
       */
      copied: () => LocalizedString;
      /**
       * 已生成页面 UI 规范
       */
      uiDocumentDetected: () => LocalizedString;
      /**
       * 应用到画布
       */
      applyToCanvas: () => LocalizedString;
      /**
       * 已成功应用到页面画布！
       */
      appliedToCanvasSuccess: () => LocalizedString;
      /**
       * 个组件元素
       */
      elementsCount: () => LocalizedString;
      /**
       * 查看 JSON 规范
       */
      viewJson: () => LocalizedString;
      /**
       * 隐藏 JSON
       */
      hideJson: () => LocalizedString;
      /**
       * App 标识
       */
      appKey: () => LocalizedString;
      /**
       * 协议版本
       */
      manifestVersion: () => LocalizedString;
      /**
       * 组件种类
       */
      componentTypes: () => LocalizedString;
      /**
       * {count} 种
       */
      componentCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 契约状态
       */
      status: () => LocalizedString;
      /**
       * 已通过
       */
      valid: () => LocalizedString;
      /**
       * 待审核
       */
      needsReview: () => LocalizedString;
      /**
       * 修订版本 {rev}
       */
      rev: (arg: { rev: unknown }) => LocalizedString;
      /**
       * 契约诊断信息
       */
      diagnostics: () => LocalizedString;
      /**
       * 提示词与上下文调试
       */
      promptInspector: () => LocalizedString;
      /**
       * 查看后端组装的完整系统提示词、用户会话历史与实时上下文。
       */
      promptInspectorDesc: () => LocalizedString;
      /**
       * 全部消息 (时间线)
       */
      allTimelineTab: () => LocalizedString;
      /**
       * 完整系统提示词
       */
      systemPromptTab: () => LocalizedString;
      /**
       * 基础提示词
       */
      basePromptTab: () => LocalizedString;
      /**
       * 注入组件
       */
      injectedComponentsTab: () => LocalizedString;
      /**
       * 用户与上下文
       */
      userContextTab: () => LocalizedString;
      /**
       * 请求数据包
       */
      rawPayloadTab: () => LocalizedString;
      /**
       * MD 文档模式
       */
      viewModeMarkdown: () => LocalizedString;
      /**
       * 原始代码
       */
      viewModeRaw: () => LocalizedString;
      /**
       * 提示词拆解
       */
      breakdown: () => LocalizedString;
      /**
       * 全局底层提示词
       */
      globalPrompt: () => LocalizedString;
      /**
       * 应用基础提示词
       */
      appSystem: () => LocalizedString;
      /**
       * 目标元素上下文
       */
      selectedElementContext: () => LocalizedString;
      /**
       * 注入组件清单
       */
      injectedComponents: () => LocalizedString;
      /**
       * 注入 OpenAPI 接口
       */
      injectedOpenApi: () => LocalizedString;
      /**
       * 当前提示词配置未注入物料组件
       */
      noInjectedComponents: () => LocalizedString;
      /**
       * 当前提示词配置未注入 OpenAPI 接口
       */
      noInjectedOpenApi: () => LocalizedString;
      /**
       * 获取最新提示词
       */
      fetchPrompt: () => LocalizedString;
      /**
       * 正在获取提示词...
       */
      fetchingPrompt: () => LocalizedString;
      /**
       * 复制提示词
       */
      copyPrompt: () => LocalizedString;
      /**
       * {count} 字符
       */
      charsCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 约 {count} tokens
       */
      estimatedTokens: (arg: { count: unknown }) => LocalizedString;
      /**
       * 开发者调试
       */
      devModeOnly: () => LocalizedString;
      /**
       * 查看提示词与调试信息
       */
      openInspector: () => LocalizedString;
    };
    tools: {
      /**
       * 可视化编辑模式
       */
      visual: () => LocalizedString;
      /**
       * 文档编辑模式
       */
      text: () => LocalizedString;
      /**
       * 开发者模式
       */
      developer: () => LocalizedString;
      /**
       * 预览模式
       */
      preview: () => LocalizedString;
    };
    actions: {
      /**
       * 动作库
       */
      title: () => LocalizedString;
      /**
       * 定义和管理可被组件直接绑定的动作与状态事件处理器。
       */
      description: () => LocalizedString;
      /**
       * 搜索动作标识、标题或类型...
       */
      searchPlaceholder: () => LocalizedString;
      /**
       * 新建动作
       */
      addAction: () => LocalizedString;
      /**
       * 编辑动作
       */
      editAction: () => LocalizedString;
      /**
       * 删除动作
       */
      deleteAction: () => LocalizedString;
      /**
       * 动作标识 (Key)
       */
      actionKey: () => LocalizedString;
      /**
       * 例如 toggleModal, updateCount
       */
      actionKeyPlaceholder: () => LocalizedString;
      /**
       * 动作名称
       */
      actionTitle: () => LocalizedString;
      /**
       * 例如 切换弹窗显示
       */
      actionTitlePlaceholder: () => LocalizedString;
      /**
       * 动作描述
       */
      actionDesc: () => LocalizedString;
      /**
       * 动作类型
       */
      actionType: () => LocalizedString;
      /**
       * 修改状态 (setState)
       */
      typeSetState: () => LocalizedString;
      /**
       * 自定义处理器 (Custom)
       */
      typeCustom: () => LocalizedString;
      /**
       * 目标状态变量
       */
      targetVariable: () => LocalizedString;
      /**
       * 目标值
       */
      targetValue: () => LocalizedString;
      /**
       * 取反切换 (!toggle)
       */
      toggleOption: () => LocalizedString;
      /**
       * 设为 true
       */
      trueOption: () => LocalizedString;
      /**
       * 设为 false
       */
      falseOption: () => LocalizedString;
      /**
       * 自定义值
       */
      customValue: () => LocalizedString;
      /**
       * {count} 处组件绑定
       */
      referencesCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 未被组件绑定
       */
      noReferences: () => LocalizedString;
      /**
       * 绑定该动作的组件与事件
       */
      referencesTitle: () => LocalizedString;
      /**
       * 确认删除动作
       */
      confirmDeleteTitle: () => LocalizedString;
      /**
       * 确定要删除动作“{name}”吗？
       */
      confirmDelete: (arg: { name: unknown }) => LocalizedString;
      /**
       * 动作“{name}”当前正被 {count} 处组件事件绑定，删除可能导致点击交互失效。确定继续吗？
       */
      confirmDeleteWithRefs: (arg: { count: unknown; name: unknown }) => LocalizedString;
      /**
       * 暂无动作定义
       */
      emptyTitle: () => LocalizedString;
      /**
       * 创建预设动作或状态更新逻辑，让按钮等组件能够一键直接绑定。
       */
      emptyDesc: () => LocalizedString;
      /**
       * 系统内置
       */
      builtInBadge: () => LocalizedString;
      /**
       * 自定义
       */
      customBadge: () => LocalizedString;
      /**
       * {count} 个动作
       */
      actionCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 参数配置 (JSON)
       */
      paramsJson: () => LocalizedString;
    };
    variables: {
      /**
       * 预览语言 (i18n)
       */
      locales: () => LocalizedString;
      /**
       * 状态变量
       */
      title: () => LocalizedString;
      /**
       * 搜索变量名或值...
       */
      searchPlaceholder: () => LocalizedString;
      /**
       * 新建变量
       */
      addVariable: () => LocalizedString;
      /**
       * 编辑变量
       */
      editVariable: () => LocalizedString;
      /**
       * 重命名变量
       */
      renameVariable: () => LocalizedString;
      /**
       * 删除变量
       */
      deleteVariable: () => LocalizedString;
      /**
       * 变量名
       */
      variableName: () => LocalizedString;
      /**
       * 类型
       */
      variableType: () => LocalizedString;
      /**
       * 变量值
       */
      variableValue: () => LocalizedString;
      /**
       * 例如 counter, userName
       */
      variableKeyPlaceholder: () => LocalizedString;
      /**
       * 变量名必须是合法标识符（字母、数字、_、$）
       */
      invalidKey: () => LocalizedString;
      /**
       * 变量名不能使用保留关键字 (i18n, lang, __scene)
       */
      reservedKey: () => LocalizedString;
      /**
       * 该变量名已存在
       */
      duplicateKey: () => LocalizedString;
      /**
       * 暂无状态变量
       */
      emptyStateTitle: () => LocalizedString;
      /**
       * 创建状态变量，在组件属性中进行数据绑定、条件判断与模板计算。
       */
      emptyStateDesc: () => LocalizedString;
      /**
       * {count} 处组件引用
       */
      referencesCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 未被组件引用
       */
      noReferences: () => LocalizedString;
      /**
       * 引用该变量的组件
       */
      referencesTitle: () => LocalizedString;
      /**
       * 确认删除变量
       */
      confirmDeleteTitle: () => LocalizedString;
      /**
       * 确定要删除变量“{name}”吗？
       */
      confirmDelete: (arg: { name: unknown }) => LocalizedString;
      /**
       * 变量“{name}”当前正被 {count} 处组件引用。删除可能导致动态绑定失效。确定继续吗？
       */
      confirmDeleteWithRefs: (arg: { count: unknown; name: unknown }) => LocalizedString;
      /**
       * 文本 (string)
       */
      typeString: () => LocalizedString;
      /**
       * 数值 (number)
       */
      typeNumber: () => LocalizedString;
      /**
       * 布尔 (boolean)
       */
      typeBoolean: () => LocalizedString;
      /**
       * 对象 (object)
       */
      typeObject: () => LocalizedString;
      /**
       * 数组 (array)
       */
      typeArray: () => LocalizedString;
      /**
       * 空值 (null)
       */
      typeNull: () => LocalizedString;
      /**
       * JSON 格式错误，请检查语法
       */
      jsonInvalid: () => LocalizedString;
      /**
       * 复制状态路径
       */
      copyPath: () => LocalizedString;
      /**
       * 已复制状态路径
       */
      pathCopied: () => LocalizedString;
      /**
       * 复制变量
       */
      duplicate: () => LocalizedString;
      /**
       * 保存
       */
      save: () => LocalizedString;
      /**
       * 取消
       */
      cancel: () => LocalizedString;
      /**
       * 删除
       */
      delete: () => LocalizedString;
      /**
       * 创建
       */
      create: () => LocalizedString;
      /**
       * {count} 个变量
       */
      variableCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * i18n 文本
       */
      localesTab: () => LocalizedString;
      /**
       * 状态变量
       */
      variablesTab: () => LocalizedString;
      /**
       * 格式化 JSON
       */
      formatJson: () => LocalizedString;
      /**
       * 展开查看
       */
      expandJson: () => LocalizedString;
      /**
       * 收起
       */
      collapseJson: () => LocalizedString;
      /**
       * 搜索语言名称或代号...
       */
      searchLocalesPlaceholder: () => LocalizedString;
      /**
       * 刷新语言选项
       */
      refreshLocales: () => LocalizedString;
      /**
       * 默认
       */
      defaultLocaleBadge: () => LocalizedString;
      /**
       * 服务器应用语言
       */
      serverLocalesTitle: () => LocalizedString;
      /**
       * 未找到匹配的语言
       */
      noLocalesFound: () => LocalizedString;
      /**
       * 添加语言变量 (lang)
       */
      addLangVariable: () => LocalizedString;
      /**
       * 系统保护
       */
      langBadge: () => LocalizedString;
      /**
       * 当前运行时的语言代码，仅可选择应用支持的语言
       */
      langVariableDesc: () => LocalizedString;
      /**
       * 确定要从状态中移除语言变量 (lang) 吗？
       */
      confirmDeleteLang: () => LocalizedString;
      /**
       * 新建键
       */
      addI18nKey: () => LocalizedString;
      /**
       * 编辑键
       */
      editI18nKey: () => LocalizedString;
      /**
       * 重命名键
       */
      renameI18nKey: () => LocalizedString;
      /**
       * 删除键
       */
      deleteI18nKey: () => LocalizedString;
      /**
       * 文本键名
       */
      i18nKeyName: () => LocalizedString;
      /**
       * 文本内容
       */
      i18nKeyValue: () => LocalizedString;
      /**
       * 例如 greeting, home.title
       */
      i18nKeyPlaceholder: () => LocalizedString;
      /**
       * 输入当前语言的文本内容...
       */
      i18nValuePlaceholder: () => LocalizedString;
      /**
       * 暂无 i18n 文本键
       */
      emptyI18nTitle: () => LocalizedString;
      /**
       * 创建 i18n 文本键，支持多语言动态切换与翻译文本管理。
       */
      emptyI18nDesc: () => LocalizedString;
      /**
       * 搜索键名或文本内容...
       */
      searchI18nPlaceholder: () => LocalizedString;
      /**
       * 当前编辑语言
       */
      currentLocale: () => LocalizedString;
      /**
       * 默认语言
       */
      defaultLocaleHint: () => LocalizedString;
      /**
       * 默认值: {val}
       */
      fallbackHint: (arg: { val: unknown }) => LocalizedString;
      /**
       * 未翻译
       */
      untranslated: () => LocalizedString;
      /**
       * 确认删除 i18n 键
       */
      confirmDeleteI18nTitle: () => LocalizedString;
      /**
       * 确定要从所有语言中删除键“{key}”吗？
       */
      confirmDeleteI18n: (arg: { key: unknown }) => LocalizedString;
      /**
       * 键“{key}”当前正被 {count} 处组件引用。删除可能导致翻译缺失。确定继续吗？
       */
      confirmDeleteI18nWithRefs: (arg: { count: unknown; key: unknown }) => LocalizedString;
      /**
       * {count} 个键
       */
      i18nKeyCount: (arg: { count: unknown }) => LocalizedString;
      /**
       * 复制 i18n 绑定表达式 ($t)
       */
      copyI18nPath: () => LocalizedString;
      /**
       * 已复制 i18n 表达式
       */
      i18nPathCopied: () => LocalizedString;
      /**
       * 选择语言
       */
      selectLocale: () => LocalizedString;
    };
  };
  toolbar: {
    /**
     * 选择
     */
    select: () => LocalizedString;
    /**
     * 交互
     */
    interact: () => LocalizedString;
    /**
     * 平移
     */
    pan: () => LocalizedString;
    /**
     * 缩放比例
     */
    zoom: () => LocalizedString;
    /**
     * 旋转设备
     */
    rotate: () => LocalizedString;
    /**
     * 恢复设备方向
     */
    restoreOrientation: () => LocalizedString;
    /**
     * 操作
     */
    actions: () => LocalizedString;
    /**
     * 全部
     */
    all: () => LocalizedString;
    /**
     * 组件
     */
    components: () => LocalizedString;
    /**
     * 未找到组件。
     */
    noComponents: () => LocalizedString;
  };
  menu: {
    /**
     * 文件
     */
    file: () => LocalizedString;
    /**
     * 编辑
     */
    edit: () => LocalizedString;
    /**
     * 视图
     */
    view: () => LocalizedString;
    /**
     * 偏好设置
     */
    preferences: () => LocalizedString;
    /**
     * 外观主题
     */
    theme: () => LocalizedString;
    /**
     * 界面语言
     */
    language: () => LocalizedString;
    /**
     * 简体中文
     */
    chinese: () => LocalizedString;
    /**
     * English
     */
    english: () => LocalizedString;
    /**
     * 保存文档
     */
    saveDocument: () => LocalizedString;
    /**
     * 复制 JSON 快照
     */
    copyJson: () => LocalizedString;
    /**
     * 撤销
     */
    undo: () => LocalizedString;
    /**
     * 重做
     */
    redo: () => LocalizedString;
    /**
     * 框架尺寸
     */
    frameSize: () => LocalizedString;
    /**
     * 设备方向
     */
    orientation: () => LocalizedString;
    /**
     * 竖向 (Portrait)
     */
    portrait: () => LocalizedString;
    /**
     * 横向 (Landscape)
     */
    landscape: () => LocalizedString;
    /**
     * 旋转方向
     */
    rotateOrientation: () => LocalizedString;
    /**
     * 手机尺寸
     */
    mobileCategory: () => LocalizedString;
    /**
     * 平板尺寸
     */
    tabletCategory: () => LocalizedString;
    /**
     * 电脑/桌面尺寸
     */
    desktopCategory: () => LocalizedString;
    /**
     * 缩放比例 ({percent}%)
     */
    zoomRatio: (arg: { percent: number }) => LocalizedString;
    /**
     * 放大
     */
    zoomIn: () => LocalizedString;
    /**
     * 缩小
     */
    zoomOut: () => LocalizedString;
    /**
     * 缩放到 100%
     */
    zoom100: () => LocalizedString;
    /**
     * 快捷键列表
     */
    shortcuts: () => LocalizedString;
    /**
     * 浅色模式
     */
    light: () => LocalizedString;
    /**
     * 深色模式
     */
    dark: () => LocalizedString;
    /**
     * 跟随系统
     */
    system: () => LocalizedString;
    /**
     * 展开大纲面板
     */
    expandSidebar: () => LocalizedString;
    /**
     * 折叠大纲面板
     */
    collapseSidebar: () => LocalizedString;
    /**
     * 显示背景图案
     */
    backgroundPattern: () => LocalizedString;
    /**
     * 画布设置…
     */
    canvasSettings: () => LocalizedString;
  };
  canvasSettings: {
    /**
     * 画布设置
     */
    title: () => LocalizedString;
    /**
     * 配置画布的显示与交互行为。
     */
    description: () => LocalizedString;
    /**
     * 背景
     */
    background: () => LocalizedString;
    /**
     * 控制画布编辑区域的背景纹理显示与样式。
     */
    backgroundDescription: () => LocalizedString;
    /**
     * 纹理
     */
    texture: () => LocalizedString;
    /**
     * 波点
     */
    dots: () => LocalizedString;
    /**
     * 网格
     */
    grid: () => LocalizedString;
  };
  properties: {
    /**
     * 属性
     */
    title: () => LocalizedString;
    /**
     * 选择节点后编辑目标 App 提供的属性 Meta。
     */
    empty: () => LocalizedString;
    /**
     * 图层名称
     */
    layerName: () => LocalizedString;
    /**
     * 条件显示 (Visibility)
     */
    visibilityTitle: () => LocalizedString;
    /**
     * 绑定状态变量或布尔表达式，值为真时渲染展示该组件。
     */
    visibilityDesc: () => LocalizedString;
    /**
     * 配置条件显示
     */
    configureVisibility: () => LocalizedString;
    /**
     * 重置 (始终显示)
     */
    resetVisibility: () => LocalizedString;
    /**
     * 事件与动作 (Events)
     */
    eventsTitle: () => LocalizedString;
    /**
     * 绑定动作
     */
    bindAction: () => LocalizedString;
    /**
     * 未配置动作
     */
    noAction: () => LocalizedString;
    /**
     * 修改状态 (setState)
     */
    actionSetState: () => LocalizedString;
    /**
     * 选择要修改的状态变量
     */
    selectVariable: () => LocalizedString;
    /**
     * 目标值
     */
    targetValue: () => LocalizedString;
    /**
     * 取反切换 (!toggle)
     */
    toggleBoolean: () => LocalizedString;
    /**
     * 画布通过目标 App iframe 进行沙箱渲染。Studio 仅通过 Preview Bridge 传递文档快照。
     */
    runtimeDesc: () => LocalizedString;
    openapi: {
      /**
       * OpenAPI 文档
       */
      docs: () => LocalizedString;
      /**
       * 当前 App 没有 OpenAPI 文档，请先在 Admin 中添加。
       */
      noDocs: () => LocalizedString;
      /**
       * OpenAPI 文档加载失败
       */
      loadFailed: () => LocalizedString;
      /**
       * 内嵌文档
       */
      embedded: () => LocalizedString;
      /**
       * 接口路径
       */
      operation: () => LocalizedString;
      /**
       * 请求方式
       */
      method: () => LocalizedString;
      /**
       * 路径参数
       */
      pathParams: () => LocalizedString;
      /**
       * 查询参数
       */
      queryParams: () => LocalizedString;
      /**
       * 请求体 JSON
       */
      body: () => LocalizedString;
      /**
       * 加载中…
       */
      loading: () => LocalizedString;
      /**
       * JSON 格式暂时无效
       */
      invalidJson: () => LocalizedString;
    };
  };
  status: {
    /**
     * 正在加载 App 会话
     */
    loadingTitle: () => LocalizedString;
    /**
     * Studio 正在等待目标 App 引导信息及其物料契约响应。
     */
    loadingDesc: () => LocalizedString;
    /**
     * 请从目标 App 打开 Studio
     */
    standaloneTitle: () => LocalizedString;
    /**
     * Studio 采用无状态架构设计。请通过 OpenScene Studio 会话从目标 App 启动，以便提供文档、物料清册及 iframe 预览环境。
     */
    standaloneDesc: () => LocalizedString;
    /**
     * 缺少必要参数 server-url
     */
    missingServerUrlTitle: () => LocalizedString;
    /**
     * Studio 遵循无本地存储架构，不内置任何默认后端地址。必须通过 URL query 参数显式提供目标后端服务地址，例如：?server-url=http://localhost:3000&sessionId=...#token=...
     */
    missingServerUrlDesc: () => LocalizedString;
    /**
     * Studio 会话不可用
     */
    sessionUnavailableTitle: () => LocalizedString;
  };
  notices: {
    /**
     * 已复制 JSON 快照到剪贴板
     */
    jsonCopied: () => LocalizedString;
    /**
     * 已向目标 App 发送保存指令
     */
    saveSent: () => LocalizedString;
    /**
     * 本地临时会话修改未持久化保存
     */
    saveNotPersisted: () => LocalizedString;
  };
  shortcuts: {
    /**
     * 快捷键指南
     */
    title: () => LocalizedString;
    /**
     * 快速切换模式和管理当前编辑会话。
     */
    description: () => LocalizedString;
    /**
     * 可视化编辑模式
     */
    visualMode: () => LocalizedString;
    /**
     * 文档编辑模式
     */
    textMode: () => LocalizedString;
    /**
     * 开发者模式
     */
    developerMode: () => LocalizedString;
    /**
     * 预览模式
     */
    previewMode: () => LocalizedString;
    /**
     * 撤销 / 重做
     */
    undoRedo: () => LocalizedString;
    /**
     * 保存文档
     */
    save: () => LocalizedString;
    /**
     * 复制 JSON 快照
     */
    copyJson: () => LocalizedString;
    /**
     * 关闭菜单或弹窗
     */
    close: () => LocalizedString;
  };
};

export type Formatters = {};
