// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "zh-CN";

export type Locales = "en-US" | "zh-CN";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * 保​存
     */
    save: string;
    /**
     * 撤​销
     */
    undo: string;
    /**
     * 重​做
     */
    redo: string;
    /**
     * 删​除
     */
    delete: string;
    /**
     * 完​成
     */
    done: string;
    /**
     * 搜​索​物​料​组​件​…
     */
    searchComponent: string;
    /**
     * 占​位​符
     */
    placeholder: string;
  };
  sidebar: {
    /**
     * 页​面
     */
    pages: string;
    /**
     * 物​料​契​约
     */
    agents: string;
    /**
     * 组​件​库
     */
    assets: string;
    /**
     * 模​式​工​具
     */
    tools: string;
    /**
     * 变​量​与​语​言
     */
    variables: string;
    /**
     * 收​起​面​板
     */
    collapse: string;
    /**
     * 展​开​大​纲
     */
    expand: string;
    /**
     * 展​开​属​性​面​板
     */
    expandProperties: string;
    /**
     * 页​面​与​图​层​大​纲
     */
    pagesTabTooltip: string;
    /**
     * 物​料​契​约
     */
    agentsTabTooltip: string;
    /**
     * 组​件​物​料​库
     */
    assetsTabTooltip: string;
    /**
     * 模​式​与​工​具
     */
    toolsTabTooltip: string;
    /**
     * 变​量​与​国​际​化
     */
    variablesTabTooltip: string;
  };
  panels: {
    pages: {
      /**
       * 页​面
       */
      pages: string;
      /**
       * 图​层
       */
      layers: string;
      /**
       * {​c​o​u​n​t​}​ ​个​节​点
       * @param {number} count
       */
      nodeCount: RequiredParams<"count">;
      /**
       * 当​前​文​档​为​空​。​添​加​第​一​个​ ​A​p​p​ ​节​点​后​，​它​会​成​为​ ​r​o​o​t​。
       */
      emptyDoc: string;
    };
    agents: {
      /**
       * A​p​p​ ​M​a​t​e​r​i​a​l​ ​契​约
       */
      title: string;
      /**
       * S​t​u​d​i​o​ ​通​过​契​约​驱​动​渲​染​，​不​维​护​本​地​固​定​组​件​目​录​。
       */
      description: string;
      /**
       * A​p​p​ ​标​识
       */
      appKey: string;
      /**
       * 协​议​版​本
       */
      manifestVersion: string;
      /**
       * 组​件​种​类
       */
      componentTypes: string;
      /**
       * {​c​o​u​n​t​}​ ​种
       * @param {number} count
       */
      componentCount: RequiredParams<"count">;
      /**
       * 契​约​状​态
       */
      status: string;
      /**
       * 已​通​过
       */
      valid: string;
      /**
       * 待​审​核
       */
      needsReview: string;
      /**
       * 修​订​版​本​ ​{​r​e​v​}
       * @param {number} rev
       */
      rev: RequiredParams<"rev">;
      /**
       * 契​约​诊​断​信​息
       */
      diagnostics: string;
    };
    assets: {
      /**
       * 物​料​组​件​库​ ​(​A​s​s​e​t​s​)
       */
      title: string;
      /**
       * 已​加​载​ ​{​c​o​u​n​t​}​ ​种​ ​A​p​p​ ​预​置​物​料​组​件​。
       * @param {number} count
       */
      description: RequiredParams<"count">;
    };
    tools: {
      /**
       * 编​辑​模​式
       */
      modes: string;
      /**
       * 可​视​化​编​辑​模​式
       */
      visual: string;
      /**
       * 文​档​编​辑​模​式
       */
      text: string;
      /**
       * 开​发​者​模​式
       */
      developer: string;
      /**
       * 预​览​模​式
       */
      preview: string;
    };
    variables: {
      /**
       * 预​览​语​言​ ​(​i​1​8​n​)
       */
      locales: string;
    };
  };
  toolbar: {
    /**
     * 选​择
     */
    select: string;
    /**
     * 交​互
     */
    interact: string;
    /**
     * 平​移
     */
    pan: string;
    /**
     * 缩​放​比​例
     */
    zoom: string;
    /**
     * 旋​转​设​备
     */
    rotate: string;
    /**
     * 恢​复​设​备​方​向
     */
    restoreOrientation: string;
    /**
     * 操​作
     */
    actions: string;
    /**
     * 全​部
     */
    all: string;
    /**
     * 组​件
     */
    components: string;
    /**
     * 未​找​到​组​件​。
     */
    noComponents: string;
  };
  menu: {
    /**
     * 文​件
     */
    file: string;
    /**
     * 编​辑
     */
    edit: string;
    /**
     * 视​图
     */
    view: string;
    /**
     * 偏​好​设​置
     */
    preferences: string;
    /**
     * 外​观​主​题
     */
    theme: string;
    /**
     * 界​面​语​言
     */
    language: string;
    /**
     * 简​体​中​文
     */
    chinese: string;
    /**
     * E​n​g​l​i​s​h
     */
    english: string;
    /**
     * 保​存​文​档
     */
    saveDocument: string;
    /**
     * 复​制​ ​J​S​O​N​ ​快​照
     */
    copyJson: string;
    /**
     * 撤​销
     */
    undo: string;
    /**
     * 重​做
     */
    redo: string;
    /**
     * 框​架​尺​寸
     */
    frameSize: string;
    /**
     * 设​备​方​向
     */
    orientation: string;
    /**
     * 竖​向​ ​(​P​o​r​t​r​a​i​t​)
     */
    portrait: string;
    /**
     * 横​向​ ​(​L​a​n​d​s​c​a​p​e​)
     */
    landscape: string;
    /**
     * 旋​转​方​向
     */
    rotateOrientation: string;
    /**
     * 手​机​尺​寸
     */
    mobileCategory: string;
    /**
     * 平​板​尺​寸
     */
    tabletCategory: string;
    /**
     * 电​脑​/​桌​面​尺​寸
     */
    desktopCategory: string;
    /**
     * 缩​放​比​例​ ​(​{​p​e​r​c​e​n​t​}​%​)
     * @param {number} percent
     */
    zoomRatio: RequiredParams<"percent">;
    /**
     * 放​大
     */
    zoomIn: string;
    /**
     * 缩​小
     */
    zoomOut: string;
    /**
     * 缩​放​到​ ​1​0​0​%
     */
    zoom100: string;
    /**
     * 快​捷​键​列​表
     */
    shortcuts: string;
    /**
     * 浅​色​模​式
     */
    light: string;
    /**
     * 深​色​模​式
     */
    dark: string;
    /**
     * 跟​随​系​统
     */
    system: string;
    /**
     * 展​开​大​纲​面​板
     */
    expandSidebar: string;
    /**
     * 折​叠​大​纲​面​板
     */
    collapseSidebar: string;
    /**
     * 显​示​背​景​图​案
     */
    backgroundPattern: string;
    /**
     * 画​布​设​置​…
     */
    canvasSettings: string;
  };
  canvasSettings: {
    /**
     * 画​布​设​置
     */
    title: string;
    /**
     * 配​置​画​布​的​显​示​与​交​互​行​为​。
     */
    description: string;
    /**
     * 背​景
     */
    background: string;
    /**
     * 控​制​画​布​编​辑​区​域​的​背​景​纹​理​显​示​与​样​式​。
     */
    backgroundDescription: string;
    /**
     * 纹​理
     */
    texture: string;
    /**
     * 波​点
     */
    dots: string;
    /**
     * 网​格
     */
    grid: string;
  };
  properties: {
    /**
     * 属​性
     */
    title: string;
    /**
     * 选​择​节​点​后​编​辑​目​标​ ​A​p​p​ ​提​供​的​属​性​ ​M​e​t​a​。
     */
    empty: string;
    /**
     * 图​层​名​称
     */
    layerName: string;
    /**
     * A​p​p​ ​独​立​运​行​时
     */
    runtimeTitle: string;
    /**
     * 画​布​通​过​目​标​ ​A​p​p​ ​i​f​r​a​m​e​ ​进​行​沙​箱​渲​染​。​S​t​u​d​i​o​ ​仅​通​过​ ​P​r​e​v​i​e​w​ ​B​r​i​d​g​e​ ​传​递​文​档​快​照​。
     */
    runtimeDesc: string;
  };
  status: {
    /**
     * 正​在​加​载​ ​A​p​p​ ​会​话
     */
    loadingTitle: string;
    /**
     * S​t​u​d​i​o​ ​正​在​等​待​目​标​ ​A​p​p​ ​引​导​信​息​及​其​物​料​契​约​响​应​。
     */
    loadingDesc: string;
    /**
     * 请​从​目​标​ ​A​p​p​ ​打​开​ ​S​t​u​d​i​o
     */
    standaloneTitle: string;
    /**
     * S​t​u​d​i​o​ ​采​用​无​状​态​架​构​设​计​。​请​通​过​ ​O​p​e​n​S​c​e​n​e​ ​S​t​u​d​i​o​ ​会​话​从​目​标​ ​A​p​p​ ​启​动​，​以​便​提​供​文​档​、​物​料​清​册​及​ ​i​f​r​a​m​e​ ​预​览​环​境​。
     */
    standaloneDesc: string;
    /**
     * 缺​少​必​要​参​数​ ​s​e​r​v​e​r​-​u​r​l
     */
    missingServerUrlTitle: string;
    /**
     * S​t​u​d​i​o​ ​遵​循​无​本​地​存​储​架​构​，​不​内​置​任​何​默​认​后​端​地​址​。​必​须​通​过​ ​U​R​L​ ​q​u​e​r​y​ ​参​数​显​式​提​供​目​标​后​端​服​务​地​址​，​例​如​：​?​s​e​r​v​e​r​-​u​r​l​=​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​0​&​s​e​s​s​i​o​n​I​d​=​.​.​.​#​t​o​k​e​n​=​.​.​.
     */
    missingServerUrlDesc: string;
    /**
     * S​t​u​d​i​o​ ​会​话​不​可​用
     */
    sessionUnavailableTitle: string;
  };
  notices: {
    /**
     * 已​复​制​ ​J​S​O​N​ ​快​照​到​剪​贴​板
     */
    jsonCopied: string;
    /**
     * 已​向​目​标​ ​A​p​p​ ​发​送​保​存​指​令
     */
    saveSent: string;
    /**
     * 本​地​临​时​会​话​修​改​未​持​久​化​保​存
     */
    saveNotPersisted: string;
  };
  shortcuts: {
    /**
     * 快​捷​键​指​南
     */
    title: string;
    /**
     * 快​速​切​换​模​式​和​管​理​当​前​编​辑​会​话​。
     */
    description: string;
    /**
     * 可​视​化​编​辑​模​式
     */
    visualMode: string;
    /**
     * 文​档​编​辑​模​式
     */
    textMode: string;
    /**
     * 开​发​者​模​式
     */
    developerMode: string;
    /**
     * 预​览​模​式
     */
    previewMode: string;
    /**
     * 撤​销​ ​/​ ​重​做
     */
    undoRedo: string;
    /**
     * 保​存​文​档
     */
    save: string;
    /**
     * 复​制​ ​J​S​O​N​ ​快​照
     */
    copyJson: string;
    /**
     * 关​闭​菜​单​或​弹​窗
     */
    close: string;
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * 保存
     */
    save: () => LocalizedString;
    /**
     * 撤销
     */
    undo: () => LocalizedString;
    /**
     * 重做
     */
    redo: () => LocalizedString;
    /**
     * 删除
     */
    delete: () => LocalizedString;
    /**
     * 完成
     */
    done: () => LocalizedString;
    /**
     * 搜索物料组件…
     */
    searchComponent: () => LocalizedString;
    /**
     * 占位符
     */
    placeholder: () => LocalizedString;
  };
  sidebar: {
    /**
     * 页面
     */
    pages: () => LocalizedString;
    /**
     * 物料契约
     */
    agents: () => LocalizedString;
    /**
     * 组件库
     */
    assets: () => LocalizedString;
    /**
     * 模式工具
     */
    tools: () => LocalizedString;
    /**
     * 变量与语言
     */
    variables: () => LocalizedString;
    /**
     * 收起面板
     */
    collapse: () => LocalizedString;
    /**
     * 展开大纲
     */
    expand: () => LocalizedString;
    /**
     * 展开属性面板
     */
    expandProperties: () => LocalizedString;
    /**
     * 页面与图层大纲
     */
    pagesTabTooltip: () => LocalizedString;
    /**
     * 物料契约
     */
    agentsTabTooltip: () => LocalizedString;
    /**
     * 组件物料库
     */
    assetsTabTooltip: () => LocalizedString;
    /**
     * 模式与工具
     */
    toolsTabTooltip: () => LocalizedString;
    /**
     * 变量与国际化
     */
    variablesTabTooltip: () => LocalizedString;
  };
  panels: {
    pages: {
      /**
       * 页面
       */
      pages: () => LocalizedString;
      /**
       * 图层
       */
      layers: () => LocalizedString;
      /**
       * {count} 个节点
       */
      nodeCount: (arg: { count: number }) => LocalizedString;
      /**
       * 当前文档为空。添加第一个 App 节点后，它会成为 root。
       */
      emptyDoc: () => LocalizedString;
    };
    agents: {
      /**
       * App Material 契约
       */
      title: () => LocalizedString;
      /**
       * Studio 通过契约驱动渲染，不维护本地固定组件目录。
       */
      description: () => LocalizedString;
      /**
       * App 标识
       */
      appKey: () => LocalizedString;
      /**
       * 协议版本
       */
      manifestVersion: () => LocalizedString;
      /**
       * 组件种类
       */
      componentTypes: () => LocalizedString;
      /**
       * {count} 种
       */
      componentCount: (arg: { count: number }) => LocalizedString;
      /**
       * 契约状态
       */
      status: () => LocalizedString;
      /**
       * 已通过
       */
      valid: () => LocalizedString;
      /**
       * 待审核
       */
      needsReview: () => LocalizedString;
      /**
       * 修订版本 {rev}
       */
      rev: (arg: { rev: number }) => LocalizedString;
      /**
       * 契约诊断信息
       */
      diagnostics: () => LocalizedString;
    };
    assets: {
      /**
       * 物料组件库 (Assets)
       */
      title: () => LocalizedString;
      /**
       * 已加载 {count} 种 App 预置物料组件。
       */
      description: (arg: { count: number }) => LocalizedString;
    };
    tools: {
      /**
       * 编辑模式
       */
      modes: () => LocalizedString;
      /**
       * 可视化编辑模式
       */
      visual: () => LocalizedString;
      /**
       * 文档编辑模式
       */
      text: () => LocalizedString;
      /**
       * 开发者模式
       */
      developer: () => LocalizedString;
      /**
       * 预览模式
       */
      preview: () => LocalizedString;
    };
    variables: {
      /**
       * 预览语言 (i18n)
       */
      locales: () => LocalizedString;
    };
  };
  toolbar: {
    /**
     * 选择
     */
    select: () => LocalizedString;
    /**
     * 交互
     */
    interact: () => LocalizedString;
    /**
     * 平移
     */
    pan: () => LocalizedString;
    /**
     * 缩放比例
     */
    zoom: () => LocalizedString;
    /**
     * 旋转设备
     */
    rotate: () => LocalizedString;
    /**
     * 恢复设备方向
     */
    restoreOrientation: () => LocalizedString;
    /**
     * 操作
     */
    actions: () => LocalizedString;
    /**
     * 全部
     */
    all: () => LocalizedString;
    /**
     * 组件
     */
    components: () => LocalizedString;
    /**
     * 未找到组件。
     */
    noComponents: () => LocalizedString;
  };
  menu: {
    /**
     * 文件
     */
    file: () => LocalizedString;
    /**
     * 编辑
     */
    edit: () => LocalizedString;
    /**
     * 视图
     */
    view: () => LocalizedString;
    /**
     * 偏好设置
     */
    preferences: () => LocalizedString;
    /**
     * 外观主题
     */
    theme: () => LocalizedString;
    /**
     * 界面语言
     */
    language: () => LocalizedString;
    /**
     * 简体中文
     */
    chinese: () => LocalizedString;
    /**
     * English
     */
    english: () => LocalizedString;
    /**
     * 保存文档
     */
    saveDocument: () => LocalizedString;
    /**
     * 复制 JSON 快照
     */
    copyJson: () => LocalizedString;
    /**
     * 撤销
     */
    undo: () => LocalizedString;
    /**
     * 重做
     */
    redo: () => LocalizedString;
    /**
     * 框架尺寸
     */
    frameSize: () => LocalizedString;
    /**
     * 设备方向
     */
    orientation: () => LocalizedString;
    /**
     * 竖向 (Portrait)
     */
    portrait: () => LocalizedString;
    /**
     * 横向 (Landscape)
     */
    landscape: () => LocalizedString;
    /**
     * 旋转方向
     */
    rotateOrientation: () => LocalizedString;
    /**
     * 手机尺寸
     */
    mobileCategory: () => LocalizedString;
    /**
     * 平板尺寸
     */
    tabletCategory: () => LocalizedString;
    /**
     * 电脑/桌面尺寸
     */
    desktopCategory: () => LocalizedString;
    /**
     * 缩放比例 ({percent}%)
     */
    zoomRatio: (arg: { percent: number }) => LocalizedString;
    /**
     * 放大
     */
    zoomIn: () => LocalizedString;
    /**
     * 缩小
     */
    zoomOut: () => LocalizedString;
    /**
     * 缩放到 100%
     */
    zoom100: () => LocalizedString;
    /**
     * 快捷键列表
     */
    shortcuts: () => LocalizedString;
    /**
     * 浅色模式
     */
    light: () => LocalizedString;
    /**
     * 深色模式
     */
    dark: () => LocalizedString;
    /**
     * 跟随系统
     */
    system: () => LocalizedString;
    /**
     * 展开大纲面板
     */
    expandSidebar: () => LocalizedString;
    /**
     * 折叠大纲面板
     */
    collapseSidebar: () => LocalizedString;
    /**
     * 显示背景图案
     */
    backgroundPattern: () => LocalizedString;
    /**
     * 画布设置…
     */
    canvasSettings: () => LocalizedString;
  };
  canvasSettings: {
    /**
     * 画布设置
     */
    title: () => LocalizedString;
    /**
     * 配置画布的显示与交互行为。
     */
    description: () => LocalizedString;
    /**
     * 背景
     */
    background: () => LocalizedString;
    /**
     * 控制画布编辑区域的背景纹理显示与样式。
     */
    backgroundDescription: () => LocalizedString;
    /**
     * 纹理
     */
    texture: () => LocalizedString;
    /**
     * 波点
     */
    dots: () => LocalizedString;
    /**
     * 网格
     */
    grid: () => LocalizedString;
  };
  properties: {
    /**
     * 属性
     */
    title: () => LocalizedString;
    /**
     * 选择节点后编辑目标 App 提供的属性 Meta。
     */
    empty: () => LocalizedString;
    /**
     * 图层名称
     */
    layerName: () => LocalizedString;
    /**
     * App 独立运行时
     */
    runtimeTitle: () => LocalizedString;
    /**
     * 画布通过目标 App iframe 进行沙箱渲染。Studio 仅通过 Preview Bridge 传递文档快照。
     */
    runtimeDesc: () => LocalizedString;
  };
  status: {
    /**
     * 正在加载 App 会话
     */
    loadingTitle: () => LocalizedString;
    /**
     * Studio 正在等待目标 App 引导信息及其物料契约响应。
     */
    loadingDesc: () => LocalizedString;
    /**
     * 请从目标 App 打开 Studio
     */
    standaloneTitle: () => LocalizedString;
    /**
     * Studio 采用无状态架构设计。请通过 OpenScene Studio 会话从目标 App 启动，以便提供文档、物料清册及 iframe 预览环境。
     */
    standaloneDesc: () => LocalizedString;
    /**
     * 缺少必要参数 server-url
     */
    missingServerUrlTitle: () => LocalizedString;
    /**
     * Studio 遵循无本地存储架构，不内置任何默认后端地址。必须通过 URL query 参数显式提供目标后端服务地址，例如：?server-url=http://localhost:3000&sessionId=...#token=...
     */
    missingServerUrlDesc: () => LocalizedString;
    /**
     * Studio 会话不可用
     */
    sessionUnavailableTitle: () => LocalizedString;
  };
  notices: {
    /**
     * 已复制 JSON 快照到剪贴板
     */
    jsonCopied: () => LocalizedString;
    /**
     * 已向目标 App 发送保存指令
     */
    saveSent: () => LocalizedString;
    /**
     * 本地临时会话修改未持久化保存
     */
    saveNotPersisted: () => LocalizedString;
  };
  shortcuts: {
    /**
     * 快捷键指南
     */
    title: () => LocalizedString;
    /**
     * 快速切换模式和管理当前编辑会话。
     */
    description: () => LocalizedString;
    /**
     * 可视化编辑模式
     */
    visualMode: () => LocalizedString;
    /**
     * 文档编辑模式
     */
    textMode: () => LocalizedString;
    /**
     * 开发者模式
     */
    developerMode: () => LocalizedString;
    /**
     * 预览模式
     */
    previewMode: () => LocalizedString;
    /**
     * 撤销 / 重做
     */
    undoRedo: () => LocalizedString;
    /**
     * 保存文档
     */
    save: () => LocalizedString;
    /**
     * 复制 JSON 快照
     */
    copyJson: () => LocalizedString;
    /**
     * 关闭菜单或弹窗
     */
    close: () => LocalizedString;
  };
};

export type Formatters = {};
